import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:image_picker/image_picker.dart';
import '../../config/app_theme.dart';
// Web専用: dart:html を使うため条件付きimport
// ignore: avoid_web_libraries_in_flutter
import '../../utils/web_file_picker.dart' if (dart.library.io) '../../utils/mobile_file_picker_stub.dart';

class CreatePostScreen extends StatefulWidget {
  const CreatePostScreen({super.key});

  @override
  State<CreatePostScreen> createState() => _CreatePostScreenState();
}

class _CreatePostScreenState extends State<CreatePostScreen> {
  final _textController = TextEditingController();
  final List<Uint8List> _imageBytes = [];
  final List<String> _imageNames = [];
  bool _isLoading = false;

  @override
  void dispose() {
    _textController.dispose();
    super.dispose();
  }

  Future<void> _pickImages() async {
    try {
      List<({String name, Uint8List bytes})> picked = [];

      if (kIsWeb) {
        final files = await WebFilePicker.pickImages();
        picked = files.map((f) => (name: f.name, bytes: f.bytes)).toList();
      } else {
        final picker = ImagePicker();
        final images = await picker.pickMultiImage(imageQuality: 70);
        for (final img in images) {
          final bytes = await img.readAsBytes();
          picked.add((name: img.name, bytes: bytes));
        }
      }

      for (final file in picked) {
        if (_imageBytes.length >= 2) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: const Text('無料プランでは画像は最大2枚までです'),
                backgroundColor: AppTheme.warning,
                behavior: SnackBarBehavior.floating,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
              ),
            );
          }
          break;
        }
        if (file.bytes.length > 500 * 1024) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: const Text('画像サイズが大きいです。500KB以下を推奨します'),
                backgroundColor: AppTheme.warning,
                behavior: SnackBarBehavior.floating,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
              ),
            );
          }
        }
        setState(() {
          _imageBytes.add(file.bytes);
          _imageNames.add(file.name);
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('画像の選択に失敗しました: $e'),
            backgroundColor: AppTheme.error,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        );
      }
    }
  }

  void _removeImage(int index) {
    setState(() {
      _imageBytes.removeAt(index);
      _imageNames.removeAt(index);
    });
  }

  Future<void> _submitPost() async {
    final text = _textController.text.trim();
    if (text.isEmpty && _imageBytes.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: const Text('テキストまたは画像を追加してください'),
          backgroundColor: AppTheme.warning,
          behavior: SnackBarBehavior.floating,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) throw Exception('ログインしてください');

      // ユーザー情報取得
      final userDoc = await FirebaseFirestore.instance
          .collection('users')
          .doc(user.uid)
          .get();
      final userData = userDoc.data() ?? {};

      String safeString(dynamic value) {
        if (value is String) return value;
        if (value is Map) return value.values.join(' ');
        return value?.toString() ?? '';
      }

      final nickname = safeString(userData['nickname']).isEmpty
          ? '名無し'
          : safeString(userData['nickname']);

      // 画像をBase64に変換
      final List<String> imageBase64List = [];
      for (final bytes in _imageBytes) {
        final base64Str = base64Encode(bytes);
        imageBase64List.add(base64Str);
      }

      // 投稿をFirestoreに保存
      await FirebaseFirestore.instance.collection('posts').add({
        'userId': user.uid,
        'userNickname': nickname,
        'userAvatarUrl': safeString(userData['avatarUrl']),
        'text': text,
        'images': [], // URL形式は空
        'imageBase64': imageBase64List, // Base64形式で保存
        'likesCount': 0,
        'commentsCount': 0,
        'autoGenerated': false,
        'tournamentId': null,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      });

      if (mounted) {
        Navigator.pop(context, true);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('投稿に失敗しました: $e'),
            backgroundColor: AppTheme.error,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final canPost =
        _textController.text.trim().isNotEmpty || _imageBytes.isNotEmpty;

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text('投稿を作成'),
        leading: IconButton(
          icon: const Icon(Icons.close),
          onPressed: () => Navigator.pop(context),
        ),
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: 12),
            child: ElevatedButton(
              onPressed: _isLoading || !canPost ? null : _submitPost,
              style: ElevatedButton.styleFrom(
                minimumSize: const Size(80, 36),
                padding: const EdgeInsets.symmetric(horizontal: 20),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
              ),
              child: _isLoading
                  ? const SizedBox(
                      width: 18,
                      height: 18,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        color: Colors.white,
                      ),
                    )
                  : const Text('投稿する'),
            ),
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(
                children: [
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      CircleAvatar(
                        radius: 22,
                        backgroundColor:
                            AppTheme.primaryColor.withValues(alpha: 0.12),
                        child: const Icon(
                          Icons.person,
                          color: AppTheme.primaryColor,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: TextField(
                          controller: _textController,
                          maxLines: null,
                          minLines: 5,
                          maxLength: 500,
                          style:
                              const TextStyle(fontSize: 16, height: 1.5),
                          decoration: const InputDecoration(
                            hintText:
                                '今日の大会はどうでしたか？\nチームメンバー募集中？\n近況を投稿してみましょう！',
                            hintStyle: TextStyle(
                              fontSize: 15,
                              color: AppTheme.textHint,
                              height: 1.5,
                            ),
                            border: InputBorder.none,
                            enabledBorder: InputBorder.none,
                            focusedBorder: InputBorder.none,
                            fillColor: Colors.transparent,
                            filled: true,
                            counterText: '',
                          ),
                          onChanged: (_) => setState(() {}),
                        ),
                      ),
                    ],
                  ),
                  // ── 画像プレビュー ──
                  if (_imageBytes.isNotEmpty) ...[
                    const SizedBox(height: 16),
                    GridView.builder(
                      shrinkWrap: true,
                      physics: const NeverScrollableScrollPhysics(),
                      gridDelegate:
                          const SliverGridDelegateWithFixedCrossAxisCount(
                        crossAxisCount: 2,
                        crossAxisSpacing: 8,
                        mainAxisSpacing: 8,
                      ),
                      itemCount: _imageBytes.length,
                      itemBuilder: (context, index) {
                        return Stack(
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(12),
                              child: Image.memory(
                                _imageBytes[index],
                                width: double.infinity,
                                height: double.infinity,
                                fit: BoxFit.cover,
                              ),
                            ),
                            Positioned(
                              top: 6,
                              right: 6,
                              child: GestureDetector(
                                onTap: () => _removeImage(index),
                                child: Container(
                                  width: 28,
                                  height: 28,
                                  decoration: BoxDecoration(
                                    color: Colors.black54,
                                    borderRadius:
                                        BorderRadius.circular(14),
                                  ),
                                  child: const Icon(
                                    Icons.close,
                                    size: 18,
                                    color: Colors.white,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        );
                      },
                    ),
                  ],
                ],
              ),
            ),
          ),
          // ── ボトムツールバー ──
          Container(
            padding: const EdgeInsets.symmetric(
                horizontal: 16, vertical: 10),
            decoration: BoxDecoration(
              color: Colors.white,
              border: Border(
                top: BorderSide(color: Colors.grey[200]!),
              ),
            ),
            child: SafeArea(
              child: Row(
                children: [
                  InkWell(
                    onTap:
                        _imageBytes.length >= 2 ? null : _pickImages,
                    borderRadius: BorderRadius.circular(8),
                    child: Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 12, vertical: 8),
                      decoration: BoxDecoration(
                        color: _imageBytes.length >= 2
                            ? Colors.grey[100]
                            : AppTheme.primaryColor
                                .withValues(alpha: 0.08),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Row(
                        children: [
                          Icon(
                            Icons.image_outlined,
                            color: _imageBytes.length >= 2
                                ? AppTheme.textHint
                                : AppTheme.primaryColor,
                            size: 22,
                          ),
                          const SizedBox(width: 6),
                          Text(
                            _imageBytes.isEmpty
                                ? '画像を追加'
                                : '${_imageBytes.length}/2枚',
                            style: TextStyle(
                              fontSize: 13,
                              fontWeight: FontWeight.w600,
                              color: _imageBytes.length >= 2
                                  ? AppTheme.textHint
                                  : AppTheme.primaryColor,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  const Spacer(),
                  Text(
                    '${_textController.text.length} / 500',
                    style: TextStyle(
                      fontSize: 13,
                      color: _textController.text.length > 450
                          ? AppTheme.warning
                          : AppTheme.textHint,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
