// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Um0UkiMw3evn6Sq8n66b4t1Ojxvp2L4',
    appId: '1:584952056517:web:9c58d1dd3ed79cd02afeac',
    messagingSenderId: '584952056517',
    projectId: 'sofvo-19d84',
    authDomain: 'sofvo-19d84.firebaseapp.com',
    storageBucket: 'sofvo-19d84.firebasestorage.app',
    measurementId: 'G-SGB6RFNZVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPJ1hZe5N4Q5FKQEVL8fNlRHDw0TpObYQ',
    appId: '1:584952056517:android:8a450aa9331e839b2afeac',
    messagingSenderId: '584952056517',
    projectId: 'sofvo-19d84',
    storageBucket: 'sofvo-19d84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAaQdMGZu_us_BplrwOq9t_ltvQWG0Pwc',
    appId: '1:584952056517:ios:9ede07a32db745ec2afeac',
    messagingSenderId: '584952056517',
    projectId: 'sofvo-19d84',
    storageBucket: 'sofvo-19d84.firebasestorage.app',
    iosBundleId: 'com.example.sofvo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAaQdMGZu_us_BplrwOq9t_ltvQWG0Pwc',
    appId: '1:584952056517:ios:9ede07a32db745ec2afeac',
    messagingSenderId: '584952056517',
    projectId: 'sofvo-19d84',
    storageBucket: 'sofvo-19d84.firebasestorage.app',
    iosBundleId: 'com.example.sofvo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Um0UkiMw3evn6Sq8n66b4t1Ojxvp2L4',
    appId: '1:584952056517:web:7217e98dd99267b22afeac',
    messagingSenderId: '584952056517',
    projectId: 'sofvo-19d84',
    authDomain: 'sofvo-19d84.firebaseapp.com',
    storageBucket: 'sofvo-19d84.firebasestorage.app',
    measurementId: 'G-J55TC11TYZ',
  );
}
